version: 2.1

# 
orbs:
  node: circleci/node@5.0.1

jobs:
  # name of the job
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      # checkout source code from GitHub
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:  |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm test
  optional_publish:
    #Assignment

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          # to let `test` job run after the `build` job
          requires:
            - build